# Generated by Django 5.2.7 on 2025-11-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('scales', '0001_initial')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScaleResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('scale_code', models.CharField(default='unknown', max_length=64, verbose_name='量表代码')),
                ('score', models.FloatField(default=0.0, verbose_name='分数')),
                ('selected_options', models.JSONField(default=list, verbose_name='选项选择')),
                ('conclusion', models.TextField(blank=True, verbose_name='结论摘要')),
                ('started_at', models.DateTimeField(verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '量表结果',
                'verbose_name_plural': '量表结果',
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='scales_scal_user_id_f49efd_idx')],
            },
        ),
    ]
