# Generated by Django 5.2.7 on 2025-11-02 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScaleConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('version', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(max_length=64)),
                ('questions', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '量表配置',
                'verbose_name_plural': '量表配置',
            },
        ),
        migrations.CreateModel(
            name='ScaleResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('selected_options', models.JSONField(default=list)),
                ('duration_ms', models.IntegerField()),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('completed', '已完成')], default='completed', max_length=16)),
                ('analysis', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scale_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='scales.scaleconfig')),
            ],
            options={
                'verbose_name': '量表结果',
                'verbose_name_plural': '量表结果',
            },
        ),
    ]
