# Generated by Django 5.2.7 on 2025-11-22 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScaleConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='量表名称')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='量表代码')),
                ('version', models.CharField(max_length=32, verbose_name='版本号')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('type', models.CharField(max_length=64, verbose_name='类型')),
                ('questions', models.JSONField(default=list, verbose_name='问题列表')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用')], default='draft', max_length=16, verbose_name='状态')),
                ('yaml_config', models.TextField(blank=True, verbose_name='YAML 配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '量表配置',
                'verbose_name_plural': '量表配置',
            },
        ),
        migrations.CreateModel(
            name='ScaleResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('selected_options', models.JSONField(default=list)),
                ('conclusion', models.TextField(blank=True, verbose_name='结论摘要')),
                ('duration_ms', models.IntegerField()),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('completed', '已完成')], default='completed', max_length=16)),
                ('analysis', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scale_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='scales.scaleconfig')),
            ],
            options={
                'verbose_name': '量表结果',
                'verbose_name_plural': '量表结果',
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='scales_scal_user_id_f49efd_idx'), models.Index(fields=['scale_config'], name='scales_scal_scale_c_07bba1_idx')],
            },
        ),
    ]
