# Generated by Django 5.2.7 on 2025-11-07 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scaleresult',
            name='conclusion',
            field=models.TextField(blank=True, verbose_name='结论摘要'),
        ),
        migrations.CreateModel(
            name='AssessmentResultGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True, verbose_name='用户ID')),
                ('flow_type', models.CharField(default='cognitive_assessment', max_length=64, verbose_name='流程类型')),
                ('status', models.CharField(choices=[('in_progress', '进行中'), ('completed', '已完成'), ('abandoned', '已放弃')], default='in_progress', max_length=16, verbose_name='状态')),
                ('current_step', models.CharField(blank=True, max_length=64, verbose_name='当前步骤')),
                ('comprehensive_analysis', models.JSONField(blank=True, default=dict, verbose_name='综合分析')),
                ('final_conclusion', models.TextField(blank=True, verbose_name='最终结论')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '评估结果分组',
                'verbose_name_plural': '评估结果分组',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='scales_asse_user_id_d53717_idx')],
            },
        ),
        migrations.AddField(
            model_name='scaleresult',
            name='result_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='scales.assessmentresultgroup', verbose_name='所属评估组'),
        ),
        migrations.AddIndex(
            model_name='scaleresult',
            index=models.Index(fields=['user_id', '-created_at'], name='scales_scal_user_id_f49efd_idx'),
        ),
        migrations.AddIndex(
            model_name='scaleresult',
            index=models.Index(fields=['result_group', 'scale_config'], name='scales_scal_result__006a77_idx'),
        ),
    ]
