# Generated by Django 5.2.7 on 2025-11-08 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0002_scaleresult_conclusion_assessmentresultgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartAssessmentRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True, verbose_name='用户ID')),
                ('strategy', models.CharField(choices=[('cognitive_screening', '认知筛查'), ('cognitive_deep', '认知深度评估')], max_length=32, verbose_name='测评策略')),
                ('status', models.CharField(choices=[('in_progress', '进行中'), ('completed', '已完成'), ('abandoned', '已放弃')], default='in_progress', max_length=16, verbose_name='状态')),
                ('current_scale_index', models.IntegerField(default=0, verbose_name='当前量表索引')),
                ('final_result', models.JSONField(blank=True, default=dict, verbose_name='最终结果')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '智能测评记录',
                'verbose_name_plural': '智能测评记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='scaleresult',
            name='result_group',
        ),
        migrations.RemoveIndex(
            model_name='scaleresult',
            name='scales_scal_result__006a77_idx',
        ),
        migrations.AddIndex(
            model_name='smartassessmentrecord',
            index=models.Index(fields=['user_id', '-created_at'], name='scales_smar_user_id_3e748d_idx'),
        ),
        migrations.AddIndex(
            model_name='smartassessmentrecord',
            index=models.Index(fields=['status', '-created_at'], name='scales_smar_status_b7e2cd_idx'),
        ),
        migrations.AddField(
            model_name='scaleresult',
            name='smart_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scale_results', to='scales.smartassessmentrecord', verbose_name='所属智能测评'),
        ),
        migrations.AddIndex(
            model_name='scaleresult',
            index=models.Index(fields=['smart_assessment', 'scale_config'], name='scales_scal_smart_a_12e162_idx'),
        ),
        migrations.DeleteModel(
            name='AssessmentResultGroup',
        ),
    ]
