# Generated by Django 5.2.7 on 2025-11-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0003_smartassessmentrecord_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartassessmentrecord',
            name='strategy',
        ),
        migrations.AddField(
            model_name='smartassessmentrecord',
            name='scale_responses',
            field=models.JSONField(blank=True, default=list, verbose_name='子量表回答选项'),
        ),
        migrations.AddField(
            model_name='smartassessmentrecord',
            name='scale_scores',
            field=models.JSONField(blank=True, default=list, verbose_name='子量表得分与评估'),
        ),
    ]
