# Generated by Django 5.2.7 on 2025-11-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0004_remove_smartassessmentrecord_strategy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scaleresult',
            name='smart_assessment',
        ),
        migrations.RemoveIndex(
            model_name='scaleresult',
            name='scales_scal_smart_a_12e162_idx',
        ),
        migrations.AddIndex(
            model_name='scaleresult',
            index=models.Index(fields=['scale_config'], name='scales_scal_scale_c_07bba1_idx'),
        ),
        migrations.DeleteModel(
            name='SmartAssessmentRecord',
        ),
    ]
