# Generated by Django 5.2.7 on 2025-11-19 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(max_length=64, verbose_name='模板ID')),
                ('message_data', models.JSONField(verbose_name='消息内容')),
                ('assessment_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', '等待发送'), ('success', '发送成功'), ('failed', '发送失败')], default='pending', max_length=20)),
                ('wechat_msg_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='微信返回的MsgID')),
                ('error_response', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '通知发送日志',
                'verbose_name_plural': '通知发送日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(max_length=64, verbose_name='微信模板ID')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='剩余次数')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_quotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户订阅额度',
                'verbose_name_plural': '用户订阅额度',
                'unique_together': {('user', 'template_id')},
            },
        ),
    ]
