# Generated by Django 5.2.7 on 2025-11-17 11:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(help_text='1-5星评分，5星为最高分', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='评分')),
                ('content', models.TextField(blank=True, default='', help_text='可选的文本反馈，最多500字', max_length=500, verbose_name='反馈内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_processed', models.BooleanField(default=False, verbose_name='已处理')),
                ('user', models.ForeignKey(blank=True, help_text='提交反馈的用户，可为空表示匿名反馈', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户反馈',
                'verbose_name_plural': '用户反馈',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='feedback_fe_created_a1f280_idx'), models.Index(fields=['user', '-created_at'], name='feedback_fe_user_id_3075a3_idx'), models.Index(fields=['rating'], name='feedback_fe_rating_c20163_idx'), models.Index(fields=['is_processed'], name='feedback_fe_is_proc_5970f1_idx')],
            },
        ),
    ]
