# Generated by Django 5.2.7 on 2025-11-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_region_user_city_user_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_completed_cognitive_assessment',
            field=models.BooleanField(default=False, verbose_name='已完成认知评估'),
        ),
    ]
