# Generated by Django 5.2.7 on 2025-11-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_has_completed_cognitive_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='has_completed_cognitive_assessment',
            field=models.BooleanField(default=False, verbose_name='已完成初次认知评估'),
        ),
    ]
