# Generated by Django 5.2.7 on 2025-11-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_has_completed_cognitive_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='score_adl',
            field=models.FloatField(blank=True, null=True, verbose_name='ADL量表分数'),
        ),
        migrations.AddField(
            model_name='user',
            name='score_gad7',
            field=models.FloatField(blank=True, null=True, verbose_name='GAD-7量表分数'),
        ),
        migrations.AddField(
            model_name='user',
            name='score_mmse',
            field=models.FloatField(blank=True, null=True, verbose_name='MMSE量表分数'),
        ),
        migrations.AddField(
            model_name='user',
            name='score_moca',
            field=models.FloatField(blank=True, null=True, verbose_name='MoCA量表分数'),
        ),
        migrations.AddField(
            model_name='user',
            name='score_phq9',
            field=models.FloatField(blank=True, null=True, verbose_name='PHQ-9量表分数'),
        ),
        migrations.AddField(
            model_name='user',
            name='score_scd',
            field=models.FloatField(blank=True, null=True, verbose_name='SCD量表分数'),
        ),
    ]
