# Generated by Django 5.2.7 on 2025-11-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_score_adl_user_score_gad7_user_score_mmse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_mood_tested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次每日情绪测试时间'),
        ),
    ]
