# Generated by Django 5.2.7 on 2025-12-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_last_mood_tested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='分组'),
        ),
    ]
