# Generated by Django 5.2.7 on 2025-12-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_tracked',
            field=models.BooleanField(default=False, verbose_name='是否跟踪'),
        ),
    ]
