# Generated by Django 5.2.7 on 2025-12-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_is_tracked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='evening_completed_today',
            field=models.BooleanField(default=False, verbose_name='今日晚上完成情况'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_completion_reset_date',
            field=models.DateField(blank=True, null=True, verbose_name='上次完成情况重置日期'),
        ),
        migrations.AddField(
            model_name='user',
            name='morning_completed_today',
            field=models.BooleanField(default=False, verbose_name='今日早上完成情况'),
        ),
    ]
