# Generated by Django 5.2.7 on 2025-11-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CognitiveAssessmentRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True, verbose_name='用户ID')),
                ('real_name', models.CharField(blank=True, default='', max_length=50, verbose_name='真实姓名')),
                ('gender', models.CharField(blank=True, default='', max_length=10, verbose_name='性别')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('education', models.CharField(blank=True, default='', max_length=20, verbose_name='学历')),
                ('province', models.CharField(blank=True, default='', max_length=50, verbose_name='所在省份')),
                ('city', models.CharField(blank=True, default='', max_length=50, verbose_name='所在城市')),
                ('district', models.CharField(blank=True, default='', max_length=50, verbose_name='所在区县')),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('score_scd', models.FloatField(blank=True, null=True, verbose_name='SCD得分')),
                ('score_mmse', models.FloatField(blank=True, null=True, verbose_name='MMSE得分')),
                ('score_moca', models.FloatField(blank=True, null=True, verbose_name='MoCA得分')),
                ('score_gad7', models.FloatField(blank=True, null=True, verbose_name='GAD7得分')),
                ('score_phq9', models.FloatField(blank=True, null=True, verbose_name='PHQ9得分')),
                ('score_adl', models.FloatField(blank=True, null=True, verbose_name='ADL得分')),
                ('score_sus', models.FloatField(blank=True, null=True, verbose_name='SUS得分')),
                ('analysis', models.JSONField(blank=True, default=dict, verbose_name='评分分析')),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '认知测评答卷',
                'verbose_name_plural': '认知测评答卷',
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='cognitive_f_user_id_c192c5_idx')],
            },
        ),
    ]
