# Generated by Django 5.2.7 on 2025-11-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive_flow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cognitiveassessmentrecord',
            name='cognitive_f_user_id_c192c5_idx',
        ),
        migrations.AlterField(
            model_name='cognitiveassessmentrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='cognitiveassessmentrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddIndex(
            model_name='cognitiveassessmentrecord',
            index=models.Index(fields=['user_id', 'province'], name='cognitive_f_user_id_71085f_idx'),
        ),
    ]
