# Generated by Django 5.2.7 on 2025-11-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive_flow', '0002_remove_cognitiveassessmentrecord_cognitive_f_user_id_c192c5_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cognitiveassessmentrecord',
            name='score_sus',
        ),
    ]
