# Generated by Django 5.2.7 on 2025-11-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive_flow', '0003_remove_cognitiveassessmentrecord_score_sus'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cognitiveassessmentrecord',
            name='cognitive_f_user_id_71085f_idx',
        ),
        migrations.RemoveField(
            model_name='cognitiveassessmentrecord',
            name='age',
        ),
        migrations.RemoveField(
            model_name='cognitiveassessmentrecord',
            name='city',
        ),
        migrations.RemoveField(
            model_name='cognitiveassessmentrecord',
            name='district',
        ),
        migrations.RemoveField(
            model_name='cognitiveassessmentrecord',
            name='education',
        ),
        migrations.RemoveField(
            model_name='cognitiveassessmentrecord',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='cognitiveassessmentrecord',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='cognitiveassessmentrecord',
            name='province',
        ),
        migrations.RemoveField(
            model_name='cognitiveassessmentrecord',
            name='real_name',
        ),
        migrations.AddIndex(
            model_name='cognitiveassessmentrecord',
            index=models.Index(fields=['user_id'], name='cognitive_f_user_id_9c6a9f_idx'),
        ),
    ]
