# Generated by Django 5.2.7 on 2025-11-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True, verbose_name='用户')),
                ('assessment_id', models.IntegerField(verbose_name='评估ID')),
                ('report_type', models.CharField(max_length=50, verbose_name='报告类型')),
                ('overall_risk', models.CharField(max_length=50, verbose_name='总体风险')),
                ('summary', models.TextField(verbose_name='摘要')),
                ('recommendations', models.JSONField(default=list, verbose_name='建议')),
                ('professional_advice', models.TextField(verbose_name='专业建议')),
                ('trend_analysis', models.TextField(verbose_name='趋势分析')),
                ('trend_data', models.JSONField(default=dict, verbose_name='趋势数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '健康报告',
                'verbose_name_plural': '健康报告',
                'ordering': ['-created_at'],
            },
        ),
    ]
