# Generated by Django 5.2.7 on 2025-11-02 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodJournal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mood_score', models.PositiveSmallIntegerField(default=5, help_text='1-10', verbose_name='情绪分数')),
                ('mood_name', models.CharField(max_length=16, verbose_name='情绪名称')),
                ('mood_emoji', models.CharField(max_length=8, verbose_name='情绪表情')),
                ('text', models.CharField(max_length=512, verbose_name='日记内容')),
                ('record_date', models.DateTimeField(verbose_name='记录日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_journals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '情绪日记',
                'verbose_name_plural': '情绪日记',
                'ordering': ['-record_date', '-created_at'],
            },
        ),
    ]
