# Generated by Django 5.2.7 on 2025-11-03 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoodJournal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mood_score', models.PositiveSmallIntegerField(default=5, help_text='1-10分', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='情绪分数')),
                ('text', models.TextField(blank=True, default='', help_text='用户自评内容，最多1000字', max_length=1000, verbose_name='日记内容')),
                ('record_date', models.DateTimeField(verbose_name='记录日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '情绪日记',
                'verbose_name_plural': '情绪日记',
                'ordering': ['-record_date', '-created_at'],
            },
        ),
    ]
