# Generated by Django 5.2.7 on 2025-11-03 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moodjournal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_journals', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddIndex(
            model_name='moodjournal',
            index=models.Index(fields=['user', '-record_date'], name='journals_mo_user_id_c2122d_idx'),
        ),
        migrations.AddIndex(
            model_name='moodjournal',
            index=models.Index(fields=['-created_at'], name='journals_mo_created_6e9a41_idx'),
        ),
    ]
