# Generated by Django 5.2.7 on 2025-11-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodjournal',
            name='mood_name',
            field=models.CharField(default='', help_text='如开心、难过等', max_length=32, verbose_name='情绪名称'),
        ),
    ]
