# Generated by Django 5.2.7 on 2025-11-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_moodjournal_mood_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodjournal',
            name='record_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='记录日期'),
        ),
    ]
