# Generated by Django 5.2.7 on 2025-11-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_alter_moodjournal_record_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moodjournal',
            name='mood_name',
        ),
        migrations.RemoveField(
            model_name='moodjournal',
            name='mood_score',
        ),
        migrations.RemoveField(
            model_name='moodjournal',
            name='text',
        ),
        migrations.RemoveField(
            model_name='moodjournal',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='moodjournal',
            name='mainMood',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='主观情绪'),
        ),
        migrations.AddField(
            model_name='moodjournal',
            name='mainMoodOther',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='其他情绪文本'),
        ),
        migrations.AddField(
            model_name='moodjournal',
            name='moodIntensity',
            field=models.IntegerField(blank=True, null=True, verbose_name='情绪强度'),
        ),
        migrations.AddField(
            model_name='moodjournal',
            name='moodSupplementTags',
            field=models.JSONField(blank=True, null=True, verbose_name='情绪补充标签'),
        ),
        migrations.AddField(
            model_name='moodjournal',
            name='moodSupplementText',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='情绪补充说明'),
        ),
    ]
