# Generated by Django 5.2.7 on 2025-12-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0004_remove_moodjournal_mood_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodjournal',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始作答时间'),
        ),
    ]
