# Generated by Django 5.2.7 on 2025-11-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('emotiontracker', '0001_initial')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True, verbose_name='用户')),
                ('depression', models.IntegerField(verbose_name='抑郁分数')),
                ('anxiety', models.IntegerField(verbose_name='焦虑分数')),
                ('energy', models.IntegerField(verbose_name='精力分数')),
                ('sleep', models.IntegerField(verbose_name='睡眠分数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name': '情绪四维度记录',
                'verbose_name_plural': '情绪四维度记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
