# Generated by Django 5.2.7 on 2025-11-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotiontracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emotionrecord',
            options={'ordering': ['-created_at'], 'verbose_name': '情绪测试', 'verbose_name_plural': '情绪测试EMA'},
        ),
        migrations.AddField(
            model_name='emotionrecord',
            name='device_info',
            field=models.JSONField(blank=True, null=True, verbose_name='设备信息'),
        ),
        migrations.AddField(
            model_name='emotionrecord',
            name='mainMood',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='主观情绪'),
        ),
        migrations.AddField(
            model_name='emotionrecord',
            name='mainMoodOther',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='其他情绪文本'),
        ),
        migrations.AddField(
            model_name='emotionrecord',
            name='moodIntensity',
            field=models.IntegerField(blank=True, null=True, verbose_name='情绪强度'),
        ),
        migrations.AddField(
            model_name='emotionrecord',
            name='moodSupplementTags',
            field=models.JSONField(blank=True, null=True, verbose_name='情绪补充标签'),
        ),
        migrations.AddField(
            model_name='emotionrecord',
            name='moodSupplementText',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='情绪补充说明'),
        ),
        migrations.AddField(
            model_name='emotionrecord',
            name='period',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='测评时间段'),
        ),
        migrations.AddField(
            model_name='emotionrecord',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='前端提交时间'),
        ),
    ]
