# Generated by Django 5.2.7 on 2025-11-19 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotiontracker', '0002_alter_emotionrecord_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotionrecord',
            name='timestamp',
        ),
    ]
