# Generated by Django 5.2.7 on 2025-11-27 11:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotiontracker', '0003_remove_emotionrecord_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionrecord',
            name='record_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='记录日期'),
        ),
        migrations.AlterField(
            model_name='emotionrecord',
            name='period',
            field=models.CharField(choices=[('morning', '早晨'), ('evening', '晚间')], max_length=16, verbose_name='测评时间段'),
        ),
        migrations.AddConstraint(
            model_name='emotionrecord',
            constraint=models.UniqueConstraint(fields=('user_id', 'record_date', 'period'), name='unique_user_date_period'),
        ),
    ]
