# Generated by Django 5.2.7 on 2025-11-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotiontracker', '0004_emotionrecord_record_date_alter_emotionrecord_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionrecord',
            name='period',
            field=models.CharField(choices=[('morning', '早晨'), ('evening', '晚间')], max_length=16, null=True, verbose_name='测评时间段'),
        ),
    ]
