# Generated by Django 5.2.7 on 2025-11-27 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotiontracker', '0005_alter_emotionrecord_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotionrecord',
            name='device_info',
        ),
    ]
