# Generated by Django 5.2.7 on 2025-12-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotiontracker', '0006_remove_emotionrecord_device_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionrecord',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始作答时间'),
        ),
    ]
